services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tile_php
    environment:
      APP_ENV: dev
      PHP_MEMORY_LIMIT: 512M
    volumes:
      - ./app:/var/www/html
    depends_on:
      db:
        condition: service_started
      manticore:
        condition: service_healthy
    ports:
      - "${APP_PORT:-8080}:8080"

  nginx:
    image: nginx:1.27-alpine
    container_name: tile_nginx
    volumes:
      - ./app/public:/var/www/html/public
      - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php:
        condition: service_started
    ports:
      - "${NGINX_PORT:-8081}:80"

  db:
    image: mariadb:11
    container_name: tile_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tile
      MYSQL_USER: tile
      MYSQL_PASSWORD: tile
    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/00_dump.sql:ro

  manticore:
    image: manticoresearch/manticore:latest
    container_name: tile_manticore
    restart: unless-stopped
    ports:
      - "${MANTICORE_PORT:-9306}:9306"
      - "${MANTICORE_HTTP_PORT:-9308}:9308"
    volumes:
      - manticore_data:/var/lib/manticore
      - ./infrastructure/manticore/manticore.conf:/etc/manticoresearch/manticore.conf
    command: ["searchd", "--config", "/etc/manticoresearch/manticore.conf", "--nodetach"]
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/lib/manticore/searchd.pid && exit 0 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  db_data:
  manticore_data:
